### ISSUE TITLE
I want four prints of the second prototype legs

### ISSUE THREAD

**Issue by mathisgag** [alexandrelafleur/Tetrabot#18]

**Comment by alexandrelafleur** [comment]
Remember to link this issue when uploading the CAD for the legs

**Comment by FAT8888** [comment]
Not print but laser cutting

**Comment by FAT8888** [comment]
![IMG_8913](https://user-images.githubusercontent.com/43555858/73310221-daae4800-41f1-11ea-9e05-fd8d4770d7d6.PNG)

**Comment by alexandrelafleur** [comment]
J'ai vu ces changes la si cest de ca que tu parles

**Comment by FAT8888** [comment]
C'est n'est pas ca
